sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull trinhpham/xiaomi-r3g-openwrt-builder

script:
  - docker run -t -e GITHUB_TOKEN=$GITHUB_TOKEN -e GIT_REPO=$TRAVIS_REPO_SLUG trinhpham/xiaomi-r3g-openwrt-builder
  
branches:
  only:
  - master
